backend:
  name: git-gateway
  branch: master
media_folder: static/assets
public_folder: /assets
collections:
  - name: article
    label: Article
    folder: content/articles
    create: true
    slug: "index"
    path: "{{title}}/index"
    editor:
      preview: false
    fields:
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
      - { name: author, label: Author }
