backend:
  name: git-gateway
  branch: master
media_folder: static/assets
public_folder: /assets
collections:
  - name: essay
    label: Essay
    folder: content/essays
    create: true
    slug: "index"
    path: "{{title}}/index"
    editor:
      preview: false
    fields:
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
      - { name: author, label: Author }
      - { name: project, label: Project, widget: select, options: ["hembrug", "cosmic radio"]}
      - { name: coverImage, label: CoverImage, widget: image, allow_multiple: false }
  - name: work
    label: Work
    folder: content/works
    create: true
    slug: "index"
    path: "{{title}}/index"
    editor:
      preview: false
    fields:
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
      - { name: author, label: Author }
      - { name: project, label: Project, widget: select, options: ["hembrug", "cosmic radio"]}
      - { name: coverImage, label: CoverImage, widget: image, allow_multiple: false }
  - name: pages
    label: Pages
    files:
      - label: "About Page"
        name: about
        file: content/pages/about.md
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Body, name: body, widget: markdown }
          - label: Team
            name: team
            widget: list
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Position, name: position, widget: string }
              - { label: Photo, name: photo, widget: image }
      - label: "Hembrug Page"
        name: hembrug
        file: content/pages/hembrug.md
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Body, name: body, widget: markdown }
          - label: Team
            name: team
            widget: list
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Position, name: position, widget: string }
              - { label: Photo, name: photo, widget: image }
      - label: "Cosmic Radio Page"
        name: cosmicRadio
        file: content/pages/cosmicRadio.md
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Body, name: body, widget: markdown }
          - label: Team
            name: team
            widget: list
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Position, name: position, widget: string }
              - { label: Photo, name: photo, widget: image }
